name: Brewers Grade
favicon: null
layout_spectrum: 0.4681286634877324
typography_spectrum: 0.12736175837926567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19440103438682854
  lightness: 0.2513916399329901
  saturation: 0.6771837493870407
  rhythmicContrast: 0.9938380082603544
purpose: []
